source 'https://rubygems.org'

gem 'rake', '13.2.1'
gem 'i18n', '1.14.5'
#gem 'json', '2.1.0'
gem 'minitest', '5.22.3'
gem 'thread_safe', '0.3.6'
gem 'tzinfo', '2.0.6'
gem 'activesupport', '7.1.3.2'
gem 'builder', '3.2.4'
gem 'activemodel', '7.1.3.2'
gem 'deep_merge', '1.2.2'
gem 'diff-lcs', '1.5.1'
gem 'multipart-post', '2.4.1'
gem 'faraday', '2.9.0'
gem 'multi_json', '1.15.0'
gem 'her', '1.1.1'
gem 'json_pure', '2.7.2'
gem 'hiera', '3.12.0'
gem 'facter', '4.7.0'
gem 'thor', '1.2.2'
gem 'librarianp', '1.1.2'
gem 'puppet_forge', '4.1.0'
gem 'rsync', '1.0.9'
gem 'librarian-puppet', '5.0.0'
gem 'metaclass', '0.0.4'
gem 'mocha', '2.2.0'
gem 'puppet-syntax', '3.3.0'
gem 'bundler', '2.5.10'
gem 'hiera-eyaml', '4.1.0'
gem 'ruby_gpg', '0.3.2'
gem 'hiera-eyaml-gpg', '0.7.4'
gem 'highline', '2.1'
# gem 'trollop', '2.9.10'
gem 'statsd-ruby', '1.5.0'
gem 'semantic_puppet', '1.1.0'
#gem 'puppet', '6.0.1'
gem 'hiera-puppet-helper', '1.0.1'
gem 'rack', '3.0.11'
gem 'puppetserver-ca', '2.7.0'
gem 'syslog', '0.1.2'
gem 'fast_gettext', '2.3.0'
gem 'racc', '1.7.3'
gem 'getoptlong', '0.2.1'
gem 'puppet', '7.30.0'
# gem 'r10k', '4.1.0'

# group :development do
  # gem 'puppet', '8.6.0'
  # gem 'puppet-lint', '2.3.6'
  # gem 'puppetlabs_spec_helper', '0.10.3'
  # gem 'puppet-lint-file_source_rights-check', '0.1.1'
  # gem 'rspec-puppet', '2.2.0'
  # gem 'rspec-support', '3.4.1'
  # gem 'rspec-core', '3.4.3'
  # gem 'rspec-expectations', '3.4.0'
  # gem 'rspec-mocks', '3.4.1'
  # gem 'rspec', '3.4.0'
  # gem 'yamllint', '0.0.9'

  # https://puppet.community/plugins/#puppet-lint
  # gem 'puppet-lint-absolute_classname-check', '0.1.3'
  # gem 'puppet-lint-alias-check', '0.1.0'
  # gem 'puppet-lint-absolute_template_path', '1.0.0'
  # gem 'puppet-lint-appends-check', '0.1.0'
  # gem 'puppet-lint-classes_and_types_beginning_with_digits-check', '0.1.0'
  # gem 'puppet-lint-empty_string-check', '0.2.1'
  # gem 'puppet-lint-file_ensure-check', '0.2.1'
  # gem 'puppet-lint-file_source_rights-check', '0.1.0'
  # gem 'puppet-lint-fileserver-check', '1.2.1'
  # # gem 'puppet-lint-global_resource-check'
  # gem 'puppet-lint-leading_zero-check', '0.1.0'
  # gem 'puppet-lint-no_symbolic_file_modes-check', '1.0.1'
  # gem 'puppet-lint-numericvariable', '1.0.0'
  # gem 'puppet-lint-package_ensure-check', '0.1.0'

  # gem 'puppet-lint-resource_reference_syntax', '1.0.8'
  # gem 'puppet-lint-roles_and_profiles-check', '0.1.0'
  # gem 'puppet-lint-security-plugins', '0.1.7'
  # gem 'puppet-lint-spaceship_operator_without_tag-check', '0.1.0'
  # gem 'puppet-lint-strict_indent-check', '2.0.1'
  # gem 'puppet-lint-trailing_comma-check', '0.3.1'
  # gem 'puppet-lint-undef_in_function-check', '0.1.0'
  # gem 'puppet-lint-unquoted_string-check', '0.2.5'
  # gem 'puppet-lint-usascii_format-check', '1.0.0'
  # gem 'puppet-lint-variable_contains_upcase', '1.0.0'
  # gem 'puppet-lint-version_comparison-check', '0.1.2'

  #gem 'puppet-maint', git: 'https://github.com/liamjbennett/puppet-maint', :ref => '8311cffcc5352ef662ad3b0da31d17057415abc8'
# end
