---
server_config::linux::systemtools: [ 'bzip2','lsof','strace','telnet','traceroute','wget','zip','curl', 'htop']
server_config::ntp::servers: [ '3.es.pool.ntp.org','1.europe.pool.ntp.org', '2.europe.pool.ntp.org','3.europe.pool.ntp.org']

puppet::server::allowed_domains: '*vagrant.local'
puppet::server::encryption_key: 'prueba dos'
puppet::server::github_ssh_key: 'test'
puppet::server::working_directory: '/etc/puppetlabs/puppet'
puppet::server::use_puppet_db: false
puppet::repository::branch: 'master'
puppet::server::db_hostname: "%{hiera('puppet::dashboard::puppet_db_server')}"

puppet::dashboard::puppetdb::port: 8081
puppet::dashboard::puppetdb::ssl_port: 8082
puppet::dashboard::listen_port: 443
puppet::dashboard::puppetdb::puppet_db_listen_port: "%{hiera('puppet::dashboard::puppetdb::ssl_port')}"
puppet::dashboard::puppetdb::puppet_db_server: "%{hiera('puppet::dashboard::puppet_db_server')}"

puppet::agent::version: '6.0.2'
puppet::agent::runinterval: 1200
puppet::agent::interval_rand_max: 600
puppet::agent::enabled: false

linux_security::enable_ssh_only_logins: true

sensu::server::version: 6.11.0-7218
sensu::server::log_level: warn
sensu::server::password: adminadmin
sensu::server::agent_entity_config_password: "%{hiera('sensu::server::password')}"
sensu::server::agent_password: "%{hiera('sensu::server::password')}"
sensu::server::namespace: sensu-system
sensu::server::validate_namespaces: true
sensu::server::api_port: 8080
sensu::server::use_ssl: false

sensu::agent::namespace: "%{::environment}"
sensu::agent::subscriptions: [ 'sensu' ]
sensu::agent::log_level: warn
sensu::agent::password: "%{hiera('sensu::server::password')}"
sensu::agent::agent_password: "%{hiera('sensu::server::password')}"
sensu::agent::agent_entity_config_password: "%{hiera('sensu::server::password')}"
sensu::agent::validate_namespaces: "%{hiera('sensu::server::validate_namespaces')}"
sensu::agent::validate_api: true
sensu::agent::validate_entity: true
sensu::agent::use_ssl: "%{hiera('sensu::server::use_ssl')}"

sensu::agent::linux_version: "%{hiera('sensu::server::version')}"
# sensu::agent::redhat_version: '1.5.0'
# sensu::agent::windows_version: '0.27.1-2'


sensu::agent::enabled: true

sensu::metrics::enable: "%{hiera('sensu::agent::enabled')}"
sensu::default_check_handlers: [ 'debug' ]
sensu::default_metric_handlers: [ 'metrics' ]
sensu::default_interval: 60
sensu::default_interval_rand_max: 20
sensu::default_occurrences: 5
sensu::default_refresh: 10
sensu::directory: '/var/sensu'

sensu::linux_ruby_path: '/opt/sensu-plugins-ruby/embedded/bin/'

sensu::influxdb::version: 1.6.4-1
sensu::influxdb::admin_user: admin
## Password is not working. It uses default one: puppetlabs
sensu::influxdb::admin_pass: adminadminadminadmin
sensu::influxdb::port: 8086
sensu::influxdb::initial_org: appfire
sensu::influxdb::initial_bucket: sensu
sensu::influxdb::influxdb_bucket_token: 7aqnZ71TiVoJBPjqZY4RJhqk5ww8XG_wf7mdp4JZl-PpWam0XJpHN47dPV1G7hbGRTeBUqqpWYUyo2mLEUyxcA==
sensu::influxdb::influxdb_bucket_port: 8086

users::cloudops_team:
  marcos.gabilondo:
    ensure: 'present'
    ssh_key_type: rsa
    ssh_key: AAAAB3NzaC1yc2EAAAADAQABAAACAQC249wVfe6ci/QnnZGwJUIeVOT9xmidLnvyl9XXuzHxNUA9XM8t6UslXb92g8n0ihGrvz4bkNdU1KcBYDklks4TBDpFcvHV01PNdLe4FgPxk5bMScsMc9IkXWcAaFJHyF7VcUdvnjwNGhOUQQiPECITlRTW82Hd8n1pZqTXzP2pKGSVP5Xp2LEw0Mv6W+pGIdT9UY0VP2prBERrle7BE3eRYxhBK57eUk4W8K24hljA5/DWbLAlafX59VfsNs5LMDhwa7f42f8yowC2gy0m728W/m9wAnW+j42IGxYUaFTjUSt0kLkccamt87UYSPxQSh/CqcK9UPPrfSDc0j2TGR7DvR74XRe1dzHZZnrLTiRVR7glX+W4+Oiv5HnymcZ6qDIGsouzKHlm79X9wunK1P0D8MGNv2EHOfZxjXLpHdWz9PleDDPPy28YpLjLwm5fdXDKi4Wzkpb9k+q8t4v/Ymaqk95dICoNdGDfevDcmudHiIVxezgzjmjKzhnqzjzwh7AcMi0ktU3n0b6rpxcT108mwULpTh2qxWBhSNsz5m3/VaFuwr+0AC2QNX5ENizdZGU4R5yc8nd5oiHbHcdMoEwGPAJuQvkTSCIqJfumUvjUwekIK3kfmGa/V7pkvl6EjLCE3txCpAbpdYtlpt3xUbN1qlXbMICZpKLmKidFKs0IwQ==
    groups: ['sudo']